default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: visapro_development
  host: localhost
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: visapro_test
  host: localhost
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
